# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 493f338ec50b1a911f97e60bfa50e32e166f3a5b62657f272c94ca119f981eded2ca69a053ffb3415303829b3fb5c7d76b1bf8ce27f780ff548e9bc9b33bc146

test:
  secret_key_base: cfc0e702ec51299efa624410f140bcd2797a56d83ce4b92201e1b5f44ad5f78b27a7ae37ca8f08a9cd267f820e5475552277b89dc3fee6bebd8c8ba56445031d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
